#!/bin/bash
# Download specific chart from Bitcoin Magazine Pro
# ⚠️ Requires authentication - documented structure only

CHART_NAME="${1:-}"
APP_NAME="${2:-}"

if [ -z "$CHART_NAME" ]; then
    echo "❌ Usage: $0 <chart_name> [app_name]"
    echo ""
    echo "Available charts:"
    echo ""
    echo "Market Cycle:"
    echo "  investor-tool      market_cycle_ma"
    echo "  200wma-heatmap    200wma_heatmap"
    echo "  stock-to-flow      stock_flow"
    echo "  fear-and-greed    fear_and_greed"
    echo "  pi-cycle-top      pi_cycle_top_indicator"
    echo "  golden-ratio      golden_ratio"
    echo "  profitable-days   profitable_day"
    echo "  rainbow-chart     rainbow"
    echo "  pi-cycle-prediction pi_cycle_top_e"
    echo "  power-law         power_law"
    echo ""
    echo "Onchain Indicators:"
    echo "  mvrv-zscore       mvrv_z"
    echo "  rhodl-ratio       rhodl_ratio"
    echo "  nupl              unreali"
    echo "  reserve-risk      re"
    echo "  realized-price    realized_price"
    echo "  vdd-multiple      vdd_multiple"
    echo "  cvdd              cvdd"
    echo "  top-cap           top_cap"
    echo "  delta-top         delta_top"
    echo "  balanced-price    balanced_price"
    echo "  terminal-price    terminal_price"
    echo ""
    echo "Mining:"
    echo "  puell-multiple    puell_multiple"
    echo "  hash-ribbons      ha"
    echo "  miner-difficulty  miner_difficulty"
    echo "  miner-revenue    miner_revenue_total"
    echo ""
    echo "Example:"
    echo "  $0 mvrv-zscore mvrv_z"
    exit 1
fi

# Use chart name as app name if not provided
APP="${APP_NAME:-$CHART_NAME}"

echo "📊 Chart: $CHART_NAME"
echo "📍 App: $APP"
echo ""
echo "⚠️  Authentication Required"
echo ""
echo "Endpoint: https://www.bitcoinmagazinepro.com/django_plotly_dash/app/$APP/_dash-layout"
echo ""
echo "To download data, you need:"
echo "  1. Professional Plan subscription"
echo "  2. Authenticated session"
echo "  3. Proper cookies/headers"
echo ""
echo "The API uses Django Plotly Dash framework and requires"
echo "proper authentication to access chart data."
